[run]
active_experiment = "brain_standard"

[stimulation.brain_standard]
freq = 130
amp = 0.02
pw = 0.2
duration = 0.5
channel = [1]
inter_phase = 50e-6

[experiments.brain_standard]
profile = "brain_standard"
real_enabled = false
description = "Standard single-channel brain stimulation test."

[experiments.brain_standard.commands.1]
name = "stim"
pw_fraction = [1]
